// dllmain.cpp : 定义 DLL 应用程序的入口点。
#include "pch.h"

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_apphhzp_entityeraser_natives_NativeUtil */

#ifndef _Included_net_apphhzp_entityeraser_natives_NativeUtil
#define _Included_net_apphhzp_entityeraser_natives_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
	JNIEXPORT jint JNICALL Java_apphhzp_lib_natives_NativeUtil_postMsg
	(JNIEnv *, jclass, jlong, jint, jlong, jlong);
	JNIEXPORT jlong JNICALL Java_apphhzp_lib_natives_NativeUtil_getActiveWindow
	(JNIEnv *, jclass);
	JNIEXPORT void JNICALL Java_apphhzp_lib_natives_NativeUtil_createMsgBox
	(JNIEnv *, jclass, jstring, jstring, jint);
	JNIEXPORT jobject JNICALL Java_apphhzp_lib_natives_NativeUtil_createInstrumentationImpl
	(JNIEnv *, jclass);
	JNIEXPORT jobjectArray JNICALL Java_apphhzp_lib_natives_NativeUtil_getInstancesOfClass
	(JNIEnv *, jclass, jclass);
#ifdef __cplusplus
}
#endif
#endif
