/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_apphhzp_entityeraser_natives_NativeUtil */

#ifndef _Included_apphhzp_lib_natives_NativeUtil
#define _Included_apphhzp_lib_natives_NativeUtil

#ifdef __cplusplus
extern "C" {
#endif
	JNIEXPORT jint JNICALL Java_apphhzp_lib_natives_NativeUtil_postMsg
	(JNIEnv *, jclass, jlong, jint, jlong, jlong);
	JNIEXPORT jlong JNICALL Java_apphhzp_lib_natives_NativeUtil_getActiveWindow
	(JNIEnv *, jclass);
	JNIEXPORT void JNICALL Java_apphhzp_lib_natives_NativeUtil_createMsgBox
	(JNIEnv *, jclass, jstring, jstring, jint);
	JNIEXPORT jobject JNICALL Java_apphhzp_lib_natives_NativeUtil_createInstrumentationImpl
	(JNIEnv *, jclass);
	JNIEXPORT jobjectArray JNICALL Java_apphhzp_lib_natives_NativeUtil_getObjectsWithTag
	(JNIEnv*, jclass, jlong);
	JNIEXPORT jobjectArray JNICALL Java_apphhzp_lib_natives_NativeUtil_getInstancesOfClass
	(JNIEnv *, jclass, jclass);
	JNIEXPORT jobject JNICALL Java_apphhzp_lib_natives_NativeUtil_createObjectInstrumentationImpl
	(JNIEnv *, jclass);
	JNIEXPORT jclass JNICALL Java_apphhzp_lib_natives_NativeUtil_defineClass(JNIEnv* env,jclass cls,jobject loader,jclass lookup,jstring name,jbyteArray data,jint offset,jint length,jobject pd,jboolean initialize,jint flags,jobject classData);
#ifdef __cplusplus
}
#endif
#endif

#ifndef _Included_apphhzp_lib_instrumentation_ObjectInstrumentationImpl
#define _Included_apphhzp_lib_instrumentation_ObjectInstrumentationImpl
#ifdef __cplusplus
extern "C" {
#endif
	JNIEXPORT void JNICALL Java_apphhzp_lib_instrumentation_ObjectInstrumentationImpl_setHeapSamplingInterval0
	(JNIEnv *, jobject,jlong,jint);
	JNIEXPORT jboolean JNICALL Java_apphhzp_lib_instrumentation_ObjectInstrumentationImpl_canHookVMObjectAllocEvents0
	(JNIEnv *, jobject,jlong);
	JNIEXPORT jboolean JNICALL Java_apphhzp_lib_instrumentation_ObjectInstrumentationImpl_canHookObjectFreeEvents0
	(JNIEnv *, jobject,jlong);
	JNIEXPORT jboolean JNICALL Java_apphhzp_lib_instrumentation_ObjectInstrumentationImpl_canHookSampledObjectAllocEvents0
	(JNIEnv *, jobject,jlong);
	JNIEXPORT void JNICALL Java_apphhzp_lib_instrumentation_ObjectInstrumentationImpl_setHasMonitors
	(JNIEnv *, jobject,jlong,jboolean);
#ifdef __cplusplus
}
#endif
#endif
